# Site settings
baseurl = "https://jhuesser.ch/"
languageCode = "en-us"
title = "Jonas Hüsser"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Jonas Hüsser"
    description = "19 year old system engineer in apprenticeship, does something with media."

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "info@jhuesser.ch"

    [params.navigation]
        brand = "@jhuesser"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Jonas Hüsser"
        subtitle = "blogger - system engineer - does something with media"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "I'm 19 years old and living in Switzerland. Currently I'm in an apprenticeship as system engineer. I can do some basic scripting and programming in PHP, bash and Powershell. I want to learn C, C++, Objective-C and Swift."
        right = "In my spare time I usually meet my friends. But I do a lot with IT and new media. Also I'm playing the mobile game ingress. You can find more informations about it, if you click the button below."

        [params.about.button]
            text = "Check out ingress"
            link = "//irzh.ch"
            icon = "key"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

      
        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "&copy; 2017 Jonas Hüsser. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Mutschellen,", "Switzerland"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/jhuesser"

            [[params.footer.social.networks]]
                icon = "fa-google-plus"
                link=  "//google.com/+JonasHüsser"
                
            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "//twitter.com/JonasHuesser"
                
            [[params.footer.social.networks]]
                icon = "fa-paper-plane"
                link=  "//telegram.me/jhuesser"
            [[params.footer.social.networks]]
                icon = "fa-spotify"
                link=  "//open.spotify.com/user/jhuesser"
            
            [[params.footer.social.networks]]
                icon = "fa-lastfm"
                link=  "//last.fm/user/jhuesser"

            [[params.footer.social.networks]]
                icon = "fa-stack-overflow"
                link=  "//stackoverflow.com/users/7123766/jonas-h%C3%BCsser"

            [[params.footer.social.networks]]
                icon = "fa-youtube"
                link=  "///www.youtube.com/c/JonasH%C3%BCsser"

        [params.footer.credits]
            title = "About this site"
            text = "I use this site for testing different things. not just with the site, but with the domain. there are a lot uf subdomains on this domain."
